### PR TITLE
Proper HUD support for head translation.

### PR DESCRIPTION
**Pull request by colingeniet**
Currently, the HUD image does not follow head movements in the horizontal directions at all, and only partially does so in the vertical direction (only some elements move, movements are capped depending on the head position...).

In theory, this is easy to fix: disable the per-element movements, and translate/scale the root canvas group following head movements - this is the first commit.

However, I am afraid that the HUD might now look bad in some conditions. For instance in landing configuration (high AoA, seat up), the velocity vector is clamped too high (moving the seat used to change the clamping range, but this is also disabled by the changes).
This will take some testing and fine tuning.

What is your opinion on this idea ?

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
I have toyed with the idea of parallax before, but never got around to make some code for it.

I guess the clamping range will have to move with the head too or something..

**Comment by colingeniet** [comment]
The problem is that changing the clamping range based on the head position is inherently unrealistic. Simply increasing the clamping range works for me, but means the velocity indicator will go out of view at high AoA if the seat is not adjusted.
How bad is that in your opinion ? Losing sight of the indicator is annoying, but the indicator is not terribly useful either once clamping starts.

**Comment by NikolaiVChr** [comment]
I am thinking, I will ask some friends also what they think.
Might be leaning for making it go out of view, not sure if the behavior it has right now is something I got from manuals, I don't remember.

**Comment by colingeniet** [comment]
The ja37 flight manual indicates (chap. 1, 15.4.1) 'the [speed vector] symbol movement caused by wind correction is limited', which I think means the indicator is clamped at least horizontally. I could not find anything more precise.

**Comment by NikolaiVChr** [comment]
Well if the pilot moves his head left the entire HUD displayed is moved left also. And the projector for the HUD must have a limit in how far from its center it can project. Ergo the speed vector can not be displayed far from center. So maybe it should just disappear when more than certain amount from center.

**Comment by NikolaiVChr** [comment]
I found this video showing the effect as head moves.
Notice that when his head is moved far to the right, some stuff is starting to be missing on the left, don't know why.

https://www.youtube.com/watch?v=pX22pbWHJa4

**Comment by colingeniet** [comment]
I have no precise explanation regarding that video, but it probably would make sense if we worked out all the optical angle limitations in the hud... I have never seen a flight simulator with such an effect, maybe we should not bother with it.

I simulated the hud total field of view limit: the hud display is limited to a 28° diameter cone (flight manual 15.3.1) around the optical axis. In the picture, nothing is displayed on the very right of the hud because it is too far off center (previously the pitch scale would have continued further to the right).
fgfs-20190731094114

**Comment by colingeniet** [comment]
Regarding the speed vector, clearly it will go out of view if one moves the head too much. My question was rather whether or not it can go out of view while the head is in the default position.

**Comment by colingeniet** [comment]
Here is a minimal change to ensure the speed vector remains useful up to ~19° AoA.

**Comment by NikolaiVChr** [comment]
I worry a little about people who raise the seat on final so they can see the touchdown point proper when landing with 15.5 AoA. That the top of the HUD will then not be viewable. Not sure how big a problem that will be..will have to be tested I guess.

**Comment by colingeniet** [comment]
It currently looks like this: landing mode at 15.5 AoA.
Seat in default position
fgfs-20190731190805
Seat all the way up
fgfs-20190731190458

**Comment by colingeniet** [comment]
With the seat down, the velocity vector goes out of sight. A bit annoying, but I don't think it is the most problematic part in trying to land without raising the seat.

With the seat up, the speed vector and the alt/heading scales become separated (because I increased the clamping range for the former but not the latter). Allowing the alt/heading scales to go further down should be possible, but it means they would also disappear with the seat down.

**Comment by NikolaiVChr** [comment]
Okay.

So there is also the horizon line, I did some code that adapt that to the seat position change. But when you move the whole canvas up and down, the horizon line will auto stay on right position, as the bore line just moves up and down in a parallel fashion. So that code have to be disabled.

If you haven't done that or don't know how to do it, I can do it after the pull request is merged.

**Comment by colingeniet** [comment]
This is already done. Unless I am mistaken, all the code that changed the hud based on the seat position relied directly or indirectly on `centerOffset` being updated to follow head height, which is what I removed.

**Comment by NikolaiVChr** [comment]
cool

**Comment by NikolaiVChr** [comment]
Ready for merge?

**Comment by colingeniet** [comment]
I don't think I will add anything right now, so feel free to merge.

Not directly related to this PR, have you seen this video ?
https://www.youtube.com/watch?v=fbSCnqFMNLc
There are some really good shots of the hud, it might come in useful.

**Comment by NikolaiVChr** [comment]
Yeah, I have seen it. :)

**Pull request merged**
