### PR TITLE
Checklists improvements

### PR DESCRIPTION
**Pull request by colingeniet**
A few improvements to the checklists.

Short changelog:
- Additional checklists: before taxi, before takeoff, after landing
- Emergency checklists: engine flameout, electrical failure, fire, based on the cockpit emergency checklist plaques
- Reorganized the checklists to follow the real ones more closely
- Separated JA37/AJ(S)37 checklists to allow model specific items/markers
- Added and fixed several markers, conditions and bindings
- Use the checklist pages feature

Changes indirectly related to the checklists:
- According to the manual, the standard startup procedure is to open the cutoff valve before engaging the starter switch, which was previously impossible (jsbsim requires the cutoff to be close when starting, I fixed it by lying to jsbsim about the cutoff state when the engine is stopped).
The cutoff switch was also in the wrong direction (forward is TILL/OPEN), and the light below it merely indicates that the cutoff valves are closed (this is all according to the ja37 manual).
- Regarding the emergency checklist plaques on both sides of the cockpit, from all the photos I could find, it seems that the textures previously named `Model/plaque-*-ja.png` are the correct ones for both the JA and AJ(S) models, and I could not find anything looking like the older `Model/plaque-*.png`. I removed the later, and renamed the former, so that all models use the (I think) correct ones.

Regards,
Colin

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Very very cool, I am however not sure that you are right about the cutoff light and the plaques.

However I will look that up, will post here when I confirm it.

Which document and where in it are you referring to when you say manual?

**Comment by NikolaiVChr** [comment]
Okay. This is the plaques anno 1994 for AJS:
image

And this is anno 2001 for AJS:
image

This is anno 2003 for JA37Di:
image

For the AJ, I do not have part 1 of the manual. I think I made those from pictures I believed to be the AJ, but I might have been mistaken.

**Comment by colingeniet** [comment]
I should have been more precise on my documents, sorry.

I have the translated JA37 manual (JA37C I think, definitively not the -D revision)
https://drive.google.com/file/d/0B8bCDRcq9BVeV2o5R2o0UU5fQnc/view
and the AJS checklists
https://drive.google.com/file/d/0B8bCDRcq9BVeaFlBZVhBanJQWjQ/view
both from this post
https://forums.eagle.ru/showthread.php?t=168144

For the cutoff light, I was referring to section 10.6.1 (p. 189) :
"before engine starting, [the] red light adjacent to the LT-KRAN switch [is on]"
and
"when both LP cocks are fully open, the light at the LT-kRAN switch goes out"

For the checklist plaques, I just looked up whatever images I could find.
The only image I found with the fire (brand) checklist on the left were from this model
https://c1.staticflickr.com/9/8347/8242571202_c1c4854a13_b.jpg
which seems to be neither an AJ nor a JA (radar is missing)
On the other hand, both the AJS (I think, a model with the round radar screen at least)
https://imodeler.com/uploads/2016/03/stellan-160316-56e91ec4a0250-1024x682.jpg
and the JA
https://i.pinimg.com/originals/00/63/b1/0063b12f4ca47be7f90d849482788e01.jpg
seem to have the fire checklist on the right

**Comment by NikolaiVChr** [comment]
Just confirmed also, you are right about the cutoff light. :)

**Comment by colingeniet** [comment]
Re-reading the paragraph about the cutoff light, I think it actually also takes the A/B cutoff into account:
"when *both* LP cocks are fully open" <- I think 'both' refers to the regular and the A/B one

If you have the same interpretation, I'll fix that before merging.

**Comment by NikolaiVChr** [comment]
Yes, I think you are right about that interpretation.

**Comment by colingeniet** [comment]
Here's the patch, I also moved the A/B cutoff check in the checklists next to the cutoff check.

**Comment by NikolaiVChr** [comment]
Another thing:

<switch name="propulsion/engine/cutoff">

That property was called cutoff-actual, the reason for that is that that property does not react well to being written to. Maybe its because its tied or something else, don't know. It just sometimes gave me trouble when writing directly to it.

Hence why I did it in nasal in ja37.nas:

input.cutoffOrig.setBoolValue(input.cutoffActual.getValue());

**Comment by colingeniet** [comment]
I am not sure that I get your previous comment.
The nasal code you included updates `/controls/engines/engine[0]/cutoff` to follow `propulsion/engine/cutoff-actual`. How is it related to `propulsion/engine/cutoff` being problematic ?

**Comment by colingeniet** [comment]
The checklists you gave me are awesome, I need to revert the incorrect changes I made and rework the rest. I'll try to do that this evening.

**Comment by NikolaiVChr** [comment]
> I am not sure that I get your previous comment.
> The nasal code you included updates `/controls/engines/engine[0]/cutoff` to follow `propulsion/engine/cutoff-actual`. How is it related to `propulsion/engine/cutoff` being problematic ?

propulsion/engine/cutoff is tied to /controls/engines/engine[0]/cutoff, so in your code when you write to propulsion/engine/cutoff you cannot be sure that what you write will not be overwritten a fraction of second later. It is best not to write to propulsion/engine/cutoff at all.

**Comment by NikolaiVChr** [comment]
So is it ready to be commited? Did you modify the autostart to the new cutoff scheme, or do you want me to do that?

**Comment by colingeniet** [comment]
The autostart still works fine with the new cutoff, I don't think it needs to be changed.
I am still working on reorganising the checklists to follow the proper JA ones. I was a bit busy recently, but I hope to have time to complete it by this weekend.

**Comment by NikolaiVChr** [comment]
Alright. Looking forward to doing a cold start off your checklist.

**Comment by colingeniet** [comment]
Here are the updated JA checklists. I still need to review the AJ ones, there might be a few changes to do.

**Comment by NikolaiVChr** [comment]
In jsb-indicator line 2026:

`<test logic="OR" value="/systems/electrical/dc-light">`

Are you sure that should be a OR? Should it not only light up if afterburner cutoff AND engine cutoff is on?

Another thing. I haven't put in the relight/restart button (återstart). I did not know how to simulate that with a jsb-engine. If you have an idea on how to do that, that suggestion would be welcome.

**Comment by colingeniet** [comment]
The cutoff properties are on when closed, and the light should go off if both cutoff valves are open, thus lit if either valve is closed (if you prefer, it is an 'and', with 'not' on both sides).

For the restart button, I am not really sure. If I remember correctly, the mig15 has a quite sophisticated in-air restart procedure (and uses jsbsim), it might be a good inspiration.
It would certainly make the restart checklist more useful, since right now the engine almost always restarts as soon as whatever made it stop is fixed. This is probably out of scope of this PR however, maybe open an issue ?

**Comment by NikolaiVChr** [comment]
alright

**Comment by NikolaiVChr** [comment]
This is not related to what you are doing with checklists, but since Josh is working on the Viggen in parallel, he told me that he wishes that you (or me) please do not change files related to control and A/P including the autopilot.nas and autoflight.nas. To avoid too many merge conflicts, he is rewriting it more or less completely. :)

**Comment by colingeniet** [comment]
Taking note not to change the controls :)

Regarding the checklists, with the previous few commits, I tried to follow the real checklists order both for the JA and the AJS. The problem is that sometimes, the order of the checklists are different for absolutely no reason.
I am considering reordering the AJS ones to make the two checklists as close as possible (at the cost of a bit of historical accuracy). I think it would be possibly less confusing for users, and easier to maintain.
What do you think ?

Aside from that, I don't currently plan to change anything else on the checklists, so feel free to merge once you are fine with it, and we have solved the previous issue.

**Comment by NikolaiVChr** [comment]
I think both options are fine, if you lean towards reordering of AJS then I am fine with that.

**Comment by colingeniet** [comment]
Here it is, in that case.

**Comment by NikolaiVChr** [comment]
Looks good, merging.

**Pull request merged**
