### PR TITLE
Many AP improvements and bug fixes.

### PR DESCRIPTION
**Pull request by it0uchpods**
9b31fee: "JA37: Fix many A/P bugs, including roll hold, pitch hold, oscilations and upgrade rate based control system to latest IV system"

Kind Regards,
Josh

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Nice, looks great, scheduled for review in coming week (when I find my joystick).

**Comment by it0uchpods** [comment]
Great!

Thanks
J

**Comment by NikolaiVChr** [comment]
Merged in, closing.

**Comment by it0uchpods** [comment]
👍

**Pull request closed without merging**
