### PR TITLE
Remote control for Rb05

### PR DESCRIPTION
**Pull request by colingeniet**
Solves #113 

The general idea is there, it needs fine tuning.
For now the controls are the same as for the cursor in the JA: either bind separate joystick axes for control, or use the main flight controls, with `y` to toggle between flight controls and missile(doesn't work yet).
Eventually the AJS will get a radar cursor and this will need to be improved, but it can wait until then.

To do:
- [x] Proximity fuse for air targets
- [x] Add the flare at the back of the Rb05 to make it usable after the engine goes off
- [x] Fix controls to allow using main stick with `y`
- [x] When firing a second Rb05, it should takes over controls, and the first one should continue on its course. Currently both will be controlled together.
- [ ] I wonder if it should maintain it's pitch without inputs, or have a lower pitch down tendency. I need to read more about this.
- [ ] Adjust sensitivity? ~~The value I set is fine when using a 4way hat to control, but really low when using proper axes.~~ HB-VANO thinks it is too sensitive instead, so I won't touch that unless other persons express an opinion.
- [x] When controlling with flight controls (with `y`) trigger is disabled (it is used to click in the JA). Currently, you will need to fire, *then* press `y` to control with main flight controls.
- [x] Depending on zoom, the flare is only visible up to ~2km, which is not enough.
- [ ] Damage is not reported if the target is not in the radar FOV at missile launch. That's because it depends on the `complete_list` computed in `radar_logic.nas`, which is not even close to being complete.

### CODE REVIEW

**Comment by colingeniet** [comment]
Force pushed (sorry) a new version. Not much changed for users, but removes some hard coded assumptions in `missile.nas`.

Firing two Rb05 together now works correctly: only the last one receives inputs.
The fuse was modified for ground targets, in order to give them a pseudo hit-box.

**Comment by colingeniet** [comment]
Sorry about yet another force push, but the commit history was quite messy.

@NikolaiVChr For me the `missile.nas` part is now final. Unless I made a mistake nothing changed since the last version except the dead code you mentioned.
I made sure to keep all the changes to `missile.nas` in a single separate commit, to make it easier in case you want to port it to another aircraft.

**Comment by colingeniet** [comment]
Ready to merge for me.
@NikolaiVChr just to confirm you are fine with the PR (in particular the changes to `missile.nas`)?

I started working on `radar-logic.nas` to solve the last issue I added to the list (no damage if target is outside of radar FOV) but I prefer to make a separate PR for this because I am touching a few other things.

**Comment by NikolaiVChr** [comment]
The remote control needs to depend on time.

Else somebody with higher FPS will get higher sensitivity, etc.

In the 2 functions in missle.nas just multiply the input with me.dt

**Comment by NikolaiVChr** [comment]
And unless there is a bug, completelist should have all contacts, in FoV or not.

**Comment by colingeniet** [comment]
> The remote control needs to depend on time.

Indeed, woops

> And unless there is a bug, completelist should have all contacts, in FoV or not.

Well there is a bug: in `processTracks`, the track is only added to `complete_list` if `trackCalc` does not return `nil`, and `trackCalc` only returns a `Contact` object once all the line of sight/FOV/range tests pass, and returns `nil` otherwise.

**Pull request merged**
