### PR TITLE
External lights rework

### PR DESCRIPTION
**Pull request by colingeniet**
Several improvements to external lights:

- Adds formation lights, rear formation spotlights, and rear navigation lights
- Moves the landing lights to their accurate position, in the nose gear bay
- Removes the strobe light (does not exist on the real aircraft)
- Removes the bottom beacon light on the JA (exists on the AJ(S), but not the JA model)
- Three position switch for navigation lights (bright, dim, off)
- The taxi light (on the nose gear) can be lit without the main landing lights
- Moves the landing light switch to its accurate position, on the front left of the cockpit (just below the emergency checklist plaque)
- Improves the MP protocol, all lights should be correctly displayed on MP models
- Re-adds light glow scaling with distance, which makes the lights significantly more visible at range, and thus actually useful in MP

On a technical note, this PR merges together the main AC3D models and the blender model from https://github.com/NikolaiVChr/flightgear-viggen-masters/

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Cool. Thats alot of light work!

**Comment by NikolaiVChr** [comment]
The lights looks really great! Will merge soon, I haven't forgotten, just been busy.

**Comment by NikolaiVChr** [comment]
Okay, I got some time to check:

I found that gearRightInnerDoor no longer fit into the fuselage. Same for gearRightOuterDoor.

**Comment by colingeniet** [comment]
Indeed, I messed up the landing gear bay on the wing. Fixed it.

**Comment by NikolaiVChr** [comment]
Nice

**Comment by NikolaiVChr** [comment]
Alright looks good now. Sorry haven't had alot of time for FG these weeks, so took me some time.

The lights looks amazing. Merging.

**Pull request merged**
