### PR TITLE
Throttle cutoff control

### LINKED ISSUE #101: Feature request: Implement high pressure cutoff
The high pressure fuel cock is controlled by the thrust lever, see JA37 english manual sec. 9 (engine) par. 2.2.3.1 and 4.
It is distinct from the low pressure fuel cock controlled by the cutoff switch.

To do:
- [x] Add high pressure cutoff logic
- [x] Implement cutoff catch (and choose which version of the implementation)
- [x] Add flight idle indent
- [x] Review positions of A/B indents (make sure to keep it coherent with A/B zones etc.)
- [x] Update autostart
- [x] Update checklists

### PR DESCRIPTION
**Pull request by colingeniet**
Closes #101

### CODE REVIEW

**Comment by colingeniet** [comment]
Ahh, the JSBSim issues in 2019.1

> I could not click on the handle

Fixed for 2019.1.1 (the binding was changing the filter property, which was not a good idea... even if it works with 2019.2).

> Furthermore I can move the throttle in the entire range when it is both below the latch and above it.
Thats not intended is it?

> Plus the launcher states dont work properly after these commits.

Can't reproduce either of those with 2019.2 nor 2019.1.1, can you be more precise?

Do you want me to test 2019.1.2 as well?

**Comment by colingeniet** [comment]
Since I've been touching the checklists, here's the critical historical accuracy change, as requested.

**Comment by NikolaiVChr** [comment]
Did you update the JA37/states folder?

**Comment by NikolaiVChr** [comment]
I will pull this and recheck for the throttle movement range

**Comment by NikolaiVChr** [comment]
I can move the handle in full range. Both before and after clicking the handle in 2019.1.2
Only tested in JA37.

**Comment by NikolaiVChr** [comment]
Hmm, maybe I misunderstood how it works.
If I move my joystick throttle to 0 while engine is running, the 3D throttle does not go all the way back I see that now.
When I then click the handle, nothing happens. But afterwards when I move the joystick throttle forward the 3D throttle starts by moving back and then moves forward.
This confuses me.

**Comment by colingeniet** [comment]
This is what I feared, it's working as intended but confusing as hell.

Idea was that clicking the throttle simulates lifting the catch (there is no 3D model which does not help), which allows to pull the throttle below idle.

> afterwards when I move the joystick throttle forward the 3D throttle starts by moving back and then moves forward.

That's the usual joystick artefact: you need to move the throttle for it to update. When you do so it starts by going back because the physical throttle is at 0 but the logical one is not (was blocked by the catch, did not update afterwards).

**Comment by Rudolf339** [comment]
Maybe I just don't understand how the Viggen throttle works, but wouldn't it be better to do it kind of like how it's done in the A-10?
The throttle goes from idle to max, and  when in idle clicking it brings it in and out of cutoff

**Comment by colingeniet** [comment]
What I had in mind was something like the mig-15, but the mig-15 has a model which explains what's going on with the catch, which is really missing here.

I could try to remodel the throttle to add a model for the catch, making it more understandable.

Otherwise I will just do it the old fashion way as Rudolf suggests (which was the other possibility I initially considered).

**Comment by colingeniet** [comment]
I'll stop with my overcomplicated ideas and implement the simple version. It's understandable, and gives more precise throttle control.

I am closing this because I need to rebase/amend everything, and I will push a new version by tomorrow hopefully.

**Pull request closed without merging**
