### PR TITLE
Various data panel bugfixes

### PR DESCRIPTION
**Pull request by colingeniet**
This fixes a few bugs I found while toying with the data panel.

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
Nice! Allow me some time to review the commits. :)

**Comment by colingeniet** [comment]
Last minute addition (sorry about that): the GPS installation status (ACDATA address 30) was inverted between input and output. However, I am not sure that I fixed it in the correct direction ! 

The readme and the input indicate 1=GPS installed:
```
readme.ja37.txt: 242:  30xbcd GPS Installed = 1, NO GPS = 0. b, c and d is ignored.
data-panel.nas : 508:  setprop("ja37/navigation/gps-installed", io);
```
A comment below and the output indicate the opposite
```
data-panel.nas: 942:  # GPS-reciever installed: 300bcd (yes), 301bcd (no)
data-panel.nas: 859:  display = sprintf("30%01d000", !getprop("ja37/navigation/gps-installed"));
```

I went with 1=GPS installed for now (it seemed more intuitive as a programmer). Do you have a source for the actual value ?

**Comment by NikolaiVChr** [comment]
Yes, I have source, but its hard to find, just tried and failed.

1= installed is probably good.

**Comment by NikolaiVChr** [comment]
Thanks for the commits, I seem to have made quite a few bugs in there.
Good to see them found and fixed.

**Pull request merged**
