### PR TITLE
Radar compass texture redo, and adds heading indicator to said compass.

### PR DESCRIPTION
**Pull request by l0k1**
Redoes the radar-compass texture, as the old one was rather lopsided. Also adds the heading indicator to the compass.

In game pic:
fgfs-screen-003

### CODE REVIEW

**Comment by NikolaiVChr** [comment]
I gotta admit, I have problems with this request because it touches the ja37.ac.

First I have some questions:

- How did you load up the ja37 into Blender?
- What export script did you use to export it with?
- Did you manually change stuff in the ja37.ac after exporting it?

Beside from that, it sure looks good, and is something that would be a nice addition to the aircraft. I just have to make sure that the import/export process is done right.

**Comment by l0k1** [comment]
Hey that's a fair concern! Should've wrote more about it earlier, sorry. 
I used your blender import/export script, and didn't manually change anything afterwords. 
I decided to put it directly in the ja-37.ac file to keep the heading indicator together with the other radar-compass models. 
I added a plane to make the heading indicator, and added a material to that, and those were the only changes performed to the ja-37 model. 
Feel free to reject/ask for more clarification/voice more concerns. This is your baby and I respect that. =]

**Comment by NikolaiVChr** [comment]
Okay, I am sorry to ask this, but could you redo your ja37.ac modification, but this time start with the official Blender file?

And I would also need to get the Blender file after you have modified it.

You can get the Blender file here:
https://github.com/NikolaiVChr/flightgear-viggen-masters

When you export, make sure NOT to merge materials (is option).
Also when you export, the scene 1 & 3 should be marked. (if in doubt how to do that come on mumble and we can talk about it)

After exporting the ac needs to be processed too, like manually adjusting all the materials, but if you want I can do that. Just need the modified Blender file.

**Comment by NikolaiVChr** [comment]
Hope I didn't discourage you.

**Comment by l0k1** [comment]
Hey, nope! It was my wife's birthday today, very busy. I'll hop on mumble and talk to you about it.

**Pull request closed without merging**
